# Generated by Django 5.2.1 on 2025-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('ELG', 'Electronic Gadgets'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=3),
        ),
    ]
